name: Build Podman from Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # ogni giorno alle 3:00 UTC

permissions:
  contents: write

jobs:
  sync-and-build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        arch: [amd64]

    steps:
      - name: Install base dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git jq ca-certificates

      - name: Fetch latest Podman release tag from upstream
        id: get_tag_podman
        run: |
          tag=$(curl -s https://api.github.com/repos/containers/podman/releases/latest | jq -r .tag_name)
          version=$(echo "$tag" | sed 's/^v//')
          echo "Ultima release: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Clone Podman upstream source at tag
        run: |
          git clone --depth 1 --branch ${{ steps.get_tag_podman.outputs.tag }} https://github.com/containers/podman.git podman-source

      - name: Fetch latest Conmon release tag from upstream
        id: get_tag_conmon
        run: |
          tag=$(curl -s https://api.github.com/repos/containers/conmon/releases/latest | jq -r .tag_name)
          version=$(echo "$tag" | sed 's/^v//')
          echo "Ultima release: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Clone Conmon upstream source at tag
        run: |
          git clone --depth 1 --branch ${{ steps.get_tag_conmon.outputs.tag }} https://github.com/containers/conmon.git conmon-source

      - name: Fetch latest Crun release tag from upstream
        id: get_tag_crun
        run: |
          tag=$(curl -s https://api.github.com/repos/containers/crun/releases/latest | jq -r .tag_name)
          version=$(echo "$tag" | sed 's/^v//')
          echo "Ultima release: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Clone Crun upstream source at tag
        run: |
          git clone --depth 1 --branch ${{ steps.get_tag_crun.outputs.tag }} https://github.com/containers/crun.git crun-source

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            btrfs-progs \
            gcc \
            git \
            iptables \
            libassuan-dev \
            libbtrfs-dev \
            libc6-dev \
            libdevmapper-dev \
            libglib2.0-dev \
            libgpgme-dev \
            libgpg-error-dev \
            libprotobuf-dev \
            libprotobuf-c-dev \
            libseccomp-dev \
            libselinux1-dev \
            libsystemd-dev \
            make \
            containernetworking-plugins \
            pkg-config \
            runc \
            uidmap

      - name: Setup Go (latest version)
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Build Podman
        working-directory: ./podman-source
        run: |
          PKGNAME="podman"
          ARCH="amd64"
          MAINTAINER="${GITHUB_ACTOR:-GitHub Actions} <mauro.cardillo@gmail.com>"
          STAGING_DIR="../$(pwd)/pkgroot"
          echo ">> [BUILD] Clean..."
          mkdir -p "$STAGING_DIR/DEBIAN"
          echo ">> [BUILD] Build Podman $VERSION..."
          make clean
          make podman podman-remote rootlessport quadlet docs completions
          echo ">> [BUILD] Install to Staging dir..."
          make install DESTDIR="$STAGING_DIR"
          
